spring.application.name=marketplace
spring.datasource.url=jdbc:mysql://localhost:3306/marketplace
spring.datasource.driverClassName=com.mysql.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=Grupo5apis
spring.jpa.hibernate.ddl-auto=update
